using Content.Client.Message;
using Content.Client.Mining;
using Content.Shared.RemoteVehicle.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Content.Client.RemoteVehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RemoteModuleCardControl : Control
{
    public RemoteVehicleModuleComponent AttachedModule;

    public event Action? OnUseButtonPressed;

    public RemoteModuleCardControl(RemoteVehicleModuleComponent moduleComp)
    {
        RobustXamlLoader.Load(this);

        AttachedModule = moduleComp;

        StyleBoxFlat style = new StyleBoxFlat(moduleComp.AccentColor);
        AccentColorPanel.PanelOverride = style;

        Name.Text = Loc.GetString(moduleComp.ModuleName);
        Desc.SetMarkup(Loc.GetString(moduleComp.ModuleDesc));

        UseButton.OnPressed += _ => OnUseButtonPressed?.Invoke();

        UpdateModuleState();
    }

    private void UpdateModuleState()
    {
        Status.SetMarkup(AttachedModule.ModuleStatus);
        UseButton.Disabled = !AttachedModule.Enabled || !AttachedModule.UseAvalible;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateModuleState();
    }
}
